latest_version = "3.1.2"

["3.1.2"]
title = "Christmas Event Over - HAPPY NEW YEAR!!"
description = """
Holiday season is over but the updates aren't. ||Lottery, slave labor and 1v1 fighting coming 2026:tm:||
"""

["3.1.1"]
title = "2025 CHRISTMAS UPDATE!"
description = """
ho ho ho its holiday season so we jolly-fied everything!!! <:pppog:871396409809698898> <a:CANDY_CANE:1452409272112513156>
‎ 
[**TRIPLE MULTIPLIER EVENT AND HUGE GIVEAWAY**](https://discord.gg/ppbot) **TO CELEBRATE THE HOLIDAYS!**
"""


["3.1"]
title = "Blackjack update!!!"
description = """
try it out now with `/casino` !!
-# christmas event coming soon :eyes:
‎ 
[**TRIPLE MULTIPLIER EVENT AND HUGE GIVEAWAY**](https://discord.gg/ppbot) **TO CELEBRATE THE NEW UPDATE!**"""

["2.0"]
title = "The pp bot revamp is complete"
description = """
- All commands will **run faster** and **look better**
- All commands have been reworked to be **user-friendly**
- **BRAND NEW** `/casino`
- **BRAND NEW MINIGAMES** FOR `/beg` `/fish` `/hunt`
- **LOWER COOLDOWNS** for [voters](https://top.gg/bot/735147633076863027/vote)
- And **SO MUCH MORE**

‎ 
[**TRIPLE MULTIPLIER EVENT AND HUGE GIVEAWAY**](https://discord.gg/ppbot) **TO CELEBRATE THE NEW UPDATE!**"""