[multipliers]
    [multipliers.PILLS]
    name = "pills"
    indefinite_article = "none"
    description = "I LOVE DRUGS!!!"
    price = 60
    purchasable = true
    gain = 1

    [multipliers.STRONG_PILLS]
    name = "stronger pills"
    indefinite_article = "none"
    description = "I think there's some cocaine and some sildenafil in these..."
    price = 500
    purchasable = true
    gain = 20

[buffs]
    [buffs.HAPPY_FLOUR]
    name = "happy flour"
    indefinite_article = "none"
    description = "Definitely not cocaine, trust me."
    price = 500
    purchasable = false
    duration = 0.5
    cooldown = 12
    multiplier = 0.05

    [buffs.APPLE]
    name = "apple"
    plural = "apples"
    description = "An apple a day keeps the doctor away!"
    price = 1000
    purchasable = false
    duration = 0.5
    specified_details = ["Gives all </hospital> surgeries a **100% success rate**"]

[tools]
    [tools.FISHING_ROD]
    name = "fishing rod"
    plural = "fishing rods"
    description = "Perfect for fishing pps."
    price = 250
    purchasable = true
    associated_command_name = "fish"

    [tools.RIFLE]
    name = "rifle"
    plural = "rifles"
    description = "Ever wanted to kill hobos and steal their pps?"
    price = 1000
    purchasable = true
    associated_command_name = "hunt"

    [tools.SHOVEL]
    name = "fragile shovel"
    plural = "fragile shovels"
    description = "This shovel is super fragile, so ONLY buy it if ur loaded as fuck"
    price = 25_000
    purchasable = true
    associated_command_name = "dig"


[useless]
    [useless.BRONZE_COIN]
    name = "bronze coin"
    plural = "bronze coins"
    description = "Completely worthless. Doesn't do anything. Don't buy this."
    price = 1000
    purchasable = true

    [useless.GOLDEN_COIN]
    name = "golden coin"
    plural = "bronze coins"
    description = "This coin is also completely useless. It doesn't do anything, and it's even more expensive. Why on earth would you buy this?"
    price = 100_000
    purchasable = true

    [useless.COOKIE]
    name = "cookie"
    plural = "cookies"
    description = "A nice, tasty chocolate chip cookie."
    price = 50
    purchasable = true

    [useless.KNIFE]
    name = "knife"
    plural = "knives"
    description = "Sometimes drastic measures are needed..."
    price = 50
    purchasable = true

[seasonal]
    [seasonal.JOLLY_DIH]
    name = "jolly dihhhhh"
    description = "this dih is SUPER jolly and will make everyone around you feel super jolly aswell"
    purchasable = false
    price = 1_000_000
    season = "CHRISTMAS 2025"

    [seasonal.ROSE_TOY]
    name = "brand-new rose toy"
    description = "A brand new rose toy, ready to be used"
    purchasable = false
    season = "2025"

    [2025_NEW_YEARS_DILDO]
    name = "2025 New Year's dildo"
    description = "happy new year!!"
    purchasable = false
    season = "2025"

    [seasonal.DISCORDGGPPBOT]
    name = "discord.gg/ppbot"
    description = "This is a sign to join :eyes:"
    purchasable = false
    season = "2022"

    [CHRISTMASTHEMED_ADULT_TOY]
    name = "Christmas themed adult toy"
    description = "merry pp-mas!"
    purchasable = false
    season = "2021"
    
    [OLD_ROTTEN_APPLES]
    name = "old rotten apples"
    description = "gross."
    purchasable = false
    season = "2025"

    [MEME_MACHINE]
    name = "old rusty meme machine"
    description = "doesn't work anymore."
    purchasable = false
    season = "2025"

    [SAD_FLOUR]
    name = "old, sad flour"
    description = "not useful when making bread"
    purchasable = false
    season = "2025"

    [SCHLOPP]
    name = "schlöpp"
    description = "IM TRAPPED IN THIS BOT"
    purchasable = false
    season = "∞"
