[chance_weights]
CLICK_THAT_BUTTON = 1


[[CLICK_THAT_BUTTON]]
object = "fish"
target = "ğŸŸ"
fails = [""]
wins = [""]
foreground_style = "blurple"
background_style = "blurple"
background_label = "ğŸŒŠ"